server:
  port: 0
spring:
  application:
    name: users
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/User
      auto-index-creation: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  profiles:
    active: default

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true