spring:
  cloud:
    gateway:
      routes:
        - id: fees
          uri: http://fees
          predicates:
            - Path=/fees/**
          filters:
            - AuthenticationFilter


        - id: exams
          uri: http://exams
          predicates:
            - Path=/exams/**
          filters:
            - AuthenticationFilter

        - id: users
          uri: http://users
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

  application:
    name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true