spring:
 cloud:
   gateway:
     routes:
       - id: fees
         uri: lb://FEES
         predicates:
           - Path=/fees/**
         filters:
           - AuthenticationFilter

       - id: exams
         uri: lb://EXAMS
         predicates:
           - Path=/exams/**
         filters:
           - AuthenticationFilter

       - id: users
         uri: lb://USERS
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true